name: ZoneClock
options:
  bundleIdPrefix: ai.e6
  deploymentTarget:
    iOS: "17.0"
targets:
  ZoneClock:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.e6.zonesync
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_ENTITLEMENTS: Sources/ZoneClock.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: ZoneClock
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    dependencies:
      - target: ZoneClockWidget
        embed: true
  ZoneClockWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: WidgetExtension
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.e6.zonesync.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "NO"
        INFOPLIST_FILE: WidgetExtension/Info.plist
        SWIFT_VERSION: "5.9"
        CODE_SIGN_ENTITLEMENTS: WidgetExtension/ZoneClockWidget.entitlements
